services:
  mineru-gradio-cpu:
    profiles: ["cpu"]
    build:
      context: ..
      dockerfile: docker/global/Dockerfile.cpu
    container_name: mineru-gradio-cpu
    restart: always
    ports:
      - "7860:7860"
    environment:
      MINERU_GRADIO_BACKEND_OPTIONS: pipeline
      MINERU_GRADIO_DEFAULT_BACKEND: pipeline
      MINERU_MODEL_SOURCE: huggingface
    entrypoint:
      - /bin/bash
      - /app/docker/global/start-gradio-cpu.sh
    command:
      - --server-name
      - 0.0.0.0
      - --server-port
      - "7860"
    ulimits:
      memlock: -1
      stack: 67108864
    ipc: host
    volumes:
      - mineru-hf-cache:/root/.cache/huggingface
      - mineru-ms-cache:/root/.cache/modelscope

  mineru-gradio-gpu:
    profiles: ["gpu"]
    build:
      context: ..
      dockerfile: docker/global/Dockerfile
    container_name: mineru-gradio-gpu
    restart: always
    ports:
      - "7860:7860"
    environment:
      MINERU_GRADIO_BACKEND_OPTIONS: vlm-auto-engine
      MINERU_GRADIO_DEFAULT_BACKEND: vlm-auto-engine
    entrypoint: mineru-gradio
    command:
      - --server-name
      - 0.0.0.0
      - --server-port
      - "7860"
      - --gpu-memory-utilization
      - "0.5"
    ulimits:
      memlock: -1
      stack: 67108864
    ipc: host
    volumes:
      - mineru-hf-cache:/root/.cache/huggingface
      - mineru-ms-cache:/root/.cache/modelscope
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]

  mineru-gradio-hybrid:
    profiles: ["hybrid"]
    build:
      context: ..
      dockerfile: docker/global/Dockerfile
    container_name: mineru-gradio-hybrid
    restart: always
    ports:
      - "7860:7860"
    environment:
      MINERU_GRADIO_BACKEND_OPTIONS: hybrid-auto-engine
      MINERU_GRADIO_DEFAULT_BACKEND: hybrid-auto-engine
    entrypoint: mineru-gradio
    command:
      - --server-name
      - 0.0.0.0
      - --server-port
      - "7860"
      - --gpu-memory-utilization
      - "0.5"
    ulimits:
      memlock: -1
      stack: 67108864
    ipc: host
    volumes:
      - mineru-hf-cache:/root/.cache/huggingface
      - mineru-ms-cache:/root/.cache/modelscope
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]

volumes:
  mineru-hf-cache:
  mineru-ms-cache:
